### ISSUE TITLE
Build fails, undeclared GOOD and CHECK_CONDITION

### ISSUE THREAD

**Issue by knuxyl** [thopiekar/rcraid-dkms#41]
Trying to build on Arch 5.14

`/home/knuxyl/builds/rcraid-dkms/arch/src/rc_msg.c:1873:70: error: ‘GOOD’ undeclared (first use in this function)
 1873 |              scp->result = DID_OK << 16 | COMMAND_COMPLETE << 8 | GOOD;
      |                                                                   ^~~~`

`/home/knuxyl/builds/rcraid-dkms/arch/src/rc_msg.c:1913:62: error: ‘CHECK_CONDITION’ undeclared (first use in this function)
 1913 |        scp->result = DID_OK << 16 | COMMAND_COMPLETE << 8 | CHECK_CONDITION;
      |                                                             ^~~~~~~~~~~~~~~`
