### ISSUE TITLE
Doesn't build with kernel 5.6

### ISSUE THREAD

**Issue by Herrie82** [thopiekar/rcraid-dkms#18]
I'm getting the following errors:

DKMS make.log for rcraid-8.1.0 for kernel 5.6.0-050600-generic (x86_64)
di 31 mrt 2020 11:32:34 CEST
make: Entering directory '/var/lib/dkms/rcraid/8.1.0/build/src'
make -C /lib/modules/5.6.0-050600-generic/build M=/var/lib/dkms/rcraid/8.1.0/build/src
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-050600-generic'
ln -sf `basename /var/lib/dkms/rcraid/8.1.0/build/src/rcblob.x86_64.o .o` /var/lib/dkms/rcraid/8.1.0/build/src/rcblob.x86_64.o
  AR      /var/lib/dkms/rcraid/8.1.0/build/src/built-in.a
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/rc_init.o
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.o
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/rc_mem_ops.o
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/rc_event.o
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/rc_config.o
  CC [M]  /var/lib/dkms/rcraid/8.1.0/build/src/vers.o
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c: In function ‘rc_vprintf’:
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c:211:17: error: storage size of ‘tv’ isn’t known
  211 |  struct timeval tv;
      |                 ^~
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c:213:18: error: storage size of ‘ts’ isn’t known
  213 |  struct timespec ts;
      |                  ^~
/var/lib/dkms/rcraid/8.1.0/build/src/rc_init.c: In function ‘rc_init_proc’:
/var/lib/dkms/rcraid/8.1.0/build/src/rc_init.c:1851:65: error: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
 1851 |                 pde = proc_create(rpe->name, 0, proc_parent, rpe->fops);
      |                                                              ~~~^~~~~~
      |                                                                 |
      |                                                                 const struct file_operations * const
In file included from /var/lib/dkms/rcraid/8.1.0/build/src/rc.h:51,
                 from /var/lib/dkms/rcraid/8.1.0/build/src/rc_init.c:38:
./include/linux/proc_fs.h:64:24: note: expected ‘const struct proc_ops *’ but argument is of type ‘const struct file_operations * const’
   64 | struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
      |                        ^~~~~~~~~~~
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c:222:3: error: implicit declaration of function ‘getnstimeofday’ [-Werror=implicit-function-declaration]
  222 |   getnstimeofday(&ts);
      |   ^~~~~~~~~~~~~~
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c:213:18: warning: unused variable ‘ts’ [-Wunused-variable]
  213 |  struct timespec ts;
      |                  ^~
/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.c:211:17: warning: unused variable ‘tv’ [-Wunused-variable]
  211 |  struct timeval tv;
      |                 ^~
cc1: some warnings being treated as errors
scripts/Makefile.build:267: recipe for target '/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.o' failed
make[2]: *** [/var/lib/dkms/rcraid/8.1.0/build/src/rc_msg.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
scripts/Makefile.build:267: recipe for target '/var/lib/dkms/rcraid/8.1.0/build/src/rc_init.o' failed
make[2]: *** [/var/lib/dkms/rcraid/8.1.0/build/src/rc_init.o] Error 1
Makefile:1683: recipe for target '/var/lib/dkms/rcraid/8.1.0/build/src' failed
make[1]: *** [/var/lib/dkms/rcraid/8.1.0/build/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-050600-generic'
Makefile:68: recipe for target 'module' failed
make: *** [module] Error 2
make: Leaving directory '/var/lib/dkms/rcraid/8.1.0/build/src'

**Comment by Herrie82** [comment]
Some possible fixes in: https://gitlab.com/snippets/1937313
